### ISSUE TITLE
Use `find_emtpy_space` for repositioning the treasure and the enemies

### ISSUE THREAD

**Issue by jaredly** [SkeletalWaffles/Board-Game-w-Character#23]
https://github.com/SkeletalWaffles/Board-Game-w-Character/blob/master/Board%20Game#L215
and 
https://github.com/SkeletalWaffles/Board-Game-w-Character/blob/master/Board%20Game#L224

**Comment by marktforsyth** [comment]
I've already done it for the treasure and it wont work for enemies

**Comment by jaredly** [comment]
won't work? Why not?

**Comment by jaredly** [comment]
and it's not done for treasure, at least not in the code on github - https://github.com/SkeletalWaffles/Board-Game-w-Character/blob/master/Board%20Game#L224
