### ISSUE TITLE
Experience points!!!

### ISSUE THREAD

**Issue by jaredly** [SkeletalWaffles/Board-Game-w-Character#32]
Now we can have a leveling system.
The first step is:
- the player has experience, starts at 0
- the player also has a level, starts at 0
- when you kill an enemy, you get experience (add a thing to the enemy dictionaries that's like "exp" for the amount of experience you get for killing that enemy)
- when you reach 50 experience, `level += 1` and experience goes back to 0

**Comment by jaredly** [comment]
you should also display the experience points in the little status line at the bottom

**Comment by marktforsyth** [comment]
should i also display the level in the status at the bottom?
